name = "v20251104"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[assets]
directory = "./EDT-Pages.github.io"
binding = "ASSETS"
run_worker_first = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改
id = "2e45d01bc8d847b8aa9d81d45970b756"				#KV数据库id
